language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn build
  - yarn docs

deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    local_dir: docs/
    keep-history: true
    on:
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true