language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn build

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master